### ISSUE TITLE
Gulpfile typo's/inconsistencies

### ISSUE THREAD

**Issue by johanbaaij** [visiblevc/wordpress-starter#1]
Thanks for these articles! Looking forward to the next parts, it's been very helpful so far.

There are a few mistakes in the Gulpfile;

* The tasks `compile-styles` and `compile-scripts` are later called as `compile-css` and `compile-js` by `gulp.watch`
* `gulp.watch` looks in `/sass/` while `compile-styles` looks in `/scss/`
* in part 2 of the series it says to create a `wp-content/themes/the-theme/assets/js` folder but the Gulpfile looks in `/scripts/ `

**Comment by karellm** [comment]
@johanbaaij Thanks for pointing out the inconsistencies. I just pushed a fix to `master`.
