### ISSUE TITLE
php-intl is missing - or - how to install extensions?

### ISSUE THREAD

**Issue by ieugen** [visiblevc/wordpress-starter#109]
Hi,

I'm using version 0.15.2 of wordpress-starter and in one place I use `MessageFormatter` to handle plurals correctly. 

Because of that I get  `Uncaught Error: Class 'MessageFormatter'`

I believe php-intl is missing and I will look into adding that, however, I imagine that I might not be the only one with the issue and having the extensions installed might be good. 

Since there are a lot of extensions, it might be ok to have a way to install them on build. 

I'll come back with feedback.

Thanks,

**Comment by ieugen** [comment]
Looking at the Dockerfile for php-7.1 image I managed to install intl with `` but it was not easy. I got some pointers from [1]. 

p.s. Debian Stretch is out with php7.

[1] https://github.com/docker-library/php/issues/57

**Comment by dsifford** [comment]
Adding extensions is easy, it just needs to be done during the initial compilation. If you'd like, try adding the extension to [this chain of extensions](https://github.com/visiblevc/wordpress-starter/blob/master/php7.1/Dockerfile#L23), compile the dockerfile, and let me know if it works. I have no problem adding it in.

**Comment by ieugen** [comment]
Hi, 

It might not be that simple for all users. Some extensions require extra dependencies as well. 

If I have a running setup, how can I rebuild my image to include the extra extensions? 

In the current setup I believe I have to publish a new image.

**Comment by dsifford** [comment]
```sh
host $ docker-compose exec -it wordpress /bin/bash
wordpress # sudo apt-get install php7.0-intl
wordpress # docker-php-ext-install intl
wordpress # service apache2 reload
```

**Comment by ieugen** [comment]
I remember the image was based on Debian Jessie which has php5.6 but I will try. Thanks.

**Comment by ieugen** [comment]
Solved using instructions from https://github.com/visiblevc/wordpress-starter/pull/111
