### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by stefanvermaas** [visiblevc/wordpress-starter#11]
Hi guys,

I came across your wordpress-starter guide and I wanted to try it out. Though I found that simple running `docker-compose up` after cloning the repo doesn't seem to "work".

It fails when the database is initialized.

This is the code output, any ideas how to fix this? Because as you can see the project doesn't use the correct address, but I've got no idea where to change it to the correct IP address.

```code
wordpress_1 | => Setup Database:
wordpress_1 | =====================================
wordpress_1 |   Database Host Address:  172.17.0.3
wordpress_1 |   Database Port number:   3306
wordpress_1 |   Database Name:          wordpress
wordpress_1 |   Database Username:      root
wordpress_1 | =====================================
mysql_1     | 2016-01-16T14:00:22.062675Z 2 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:27.068629Z 3 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:32.074264Z 4 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:37.079987Z 5 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:42.085466Z 6 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:47.092656Z 7 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:52.097648Z 8 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:00:57.102063Z 9 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:01:02.107606Z 10 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
mysql_1     | 2016-01-16T14:01:07.111878Z 11 [Note] Access denied for user 'root'@'172.17.0.2' (using password: YES)
wordpress_1 | Cannot connect to Mysql
```

Cheers!

**Comment by karellm** [comment]
@stefanvermaas Can you tell me about the environment you are running this on? Also could you share with me the result of this command: `docker-compose run wordpress env`?

**Comment by stefanvermaas** [comment]
Hi @karellm,

This is the output:

```shell
stefan.vermaas at nvc2443 using 2.2.3 in ~/code/merwede-valves on master
± docker-compose run wordpress env
Starting myproject_data_1
Starting myproject_mysql_1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=f5fa77344f41
TERM=xterm
MERWEDEVALVES_MYSQL_1_PORT=tcp://172.17.0.3:3306
MERWEDEVALVES_MYSQL_1_PORT_3306_TCP=tcp://172.17.0.3:3306
MERWEDEVALVES_MYSQL_1_PORT_3306_TCP_ADDR=172.17.0.3
MERWEDEVALVES_MYSQL_1_PORT_3306_TCP_PORT=3306
MERWEDEVALVES_MYSQL_1_PORT_3306_TCP_PROTO=tcp
MERWEDEVALVES_MYSQL_1_NAME=/myproject_wordpress_run_1/merwedevalves_mysql_1
MERWEDEVALVES_MYSQL_1_ENV_MYSQL_ROOT_PASSWORD=root
MERWEDEVALVES_MYSQL_1_ENV_affinity:container==8ac34d1deb67b134f2dc906defa2415158cd3021ebcc1701a99d917b28942960
MERWEDEVALVES_MYSQL_1_ENV_MYSQL_MAJOR=5.7
MERWEDEVALVES_MYSQL_1_ENV_MYSQL_VERSION=5.7.10-1debian8
MYSQL_PORT=tcp://172.17.0.3:3306
MYSQL_PORT_3306_TCP=tcp://172.17.0.3:3306
MYSQL_PORT_3306_TCP_ADDR=172.17.0.3
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_PORT_3306_TCP_PROTO=tcp
MYSQL_NAME=/myproject_wordpress_run_1/mysql
MYSQL_ENV_MYSQL_ROOT_PASSWORD=root
MYSQL_ENV_affinity:container==8ac34d1deb67b134f2dc906defa2415158cd3021ebcc1701a99d917b28942960
MYSQL_ENV_MYSQL_MAJOR=5.7
MYSQL_ENV_MYSQL_VERSION=5.7.10-1debian8
MYSQL_1_PORT=tcp://172.17.0.3:3306
MYSQL_1_PORT_3306_TCP=tcp://172.17.0.3:3306
MYSQL_1_PORT_3306_TCP_ADDR=172.17.0.3
MYSQL_1_PORT_3306_TCP_PORT=3306
MYSQL_1_PORT_3306_TCP_PROTO=tcp
MYSQL_1_NAME=/myproject_wordpress_run_1/mysql_1
MYSQL_1_ENV_MYSQL_ROOT_PASSWORD=root
MYSQL_1_ENV_affinity:container==8ac34d1deb67b134f2dc906defa2415158cd3021ebcc1701a99d917b28942960
MYSQL_1_ENV_MYSQL_MAJOR=5.7
MYSQL_1_ENV_MYSQL_VERSION=5.7.10-1debian8
DB_NAME=wordpress
ALLOW_OVERRIDE=**False**
HOME=/root
```

**Comment by karellm** [comment]
What OS and docker setup are you running the project from? Also, are you sure you haven't touched anything? I just cloned it and it runs fine for me.

**Comment by stefanvermaas** [comment]
I'm absolutely sure I didn't touch anything, except changing the name of the project. So instead of `git clone https://github.com/visiblevc/wordpress-starter the-project` I did `git clone https://github.com/visiblevc/wordpress-starter my-project`. That's the only change.

I'm on `OS X - El Capitan (10.11.2)`, with the `Docker version 1.9.1, build a34a1d5`.

I just cloned it again to test it, and it still breaks.

**Comment by karellm** [comment]
I just upgraded to `1.9.1` to test and still works. Do you have other Docker project that run properly?

**Comment by stefanvermaas** [comment]
To be honest: no. This is the first project for which I'm trying Docker. Although the tutorial on the docker website did work.

**Comment by karellm** [comment]
I will test on a fresh docker machine tomorrow. It might be that I forgot to push the latest image to docker hub. I will also make sure to lock version to avoid that issue.

**Comment by stefanvermaas** [comment]
Thanks for looking into it! I'll await your answer :)

**Comment by karellm** [comment]
@stefanvermaas Sorry for the long delay. We just updated the project to work with Docker-Compose 1.6+. Could you update your version of docker and docker-compose and test again?

Make sure you grab the latest image too. It should be `0.2.0`.

**Comment by dsifford** [comment]
@stefanvermaas I know what the problem is. I'll include the fix in the next PR. Follow the discussion on #16

**Comment by karellm** [comment]
@stefanvermaas Can you please try the latest version of the project. `0.3.0` shouldn't have this issue. Note that a lot changed so might want to reread the tutorial.

**Comment by stefanvermaas** [comment]
I'll try it tomorrow night! Thanks for the heads up.
