### ISSUE TITLE
Debugging question

### ISSUE THREAD

**Issue by krzysztofp** [visiblevc/wordpress-starter#116]
Hello,

Really nice set-up, good work!

I have a workflow / general question on debugging WP on local environment when using this set-up.

In my normal workflow I can add echo/print to the php code including plugins and wp-core (of course I'll remove it once I've found the issue) - but with your set-up I don't have easy access from the host machine to the wp and plugins code.

What do you recommend in cases I have a tricky error to debug and need to also search through the  vendor code, not just my own theme or my own plugin code.

Many thanks for the info!

**Comment by dsifford** [comment]
@krzysztofp vim (and also likely nano) is available in the wordpress container so if you need to make any edits to built-in files the method of doing that would be to open an interactive session in the wordpress container and edit that way..

So, for example..

```sh
# host
$ docker-compose exec wordpress /bin/bash
# wordpress container
$ vim /app/path/to/file
```
...etc.

The alternative would be to create a volume of the entire `/app` directory, but that defeats the purpose of containerization IMHO.
