### ISSUE TITLE
auto deploy release?

### ISSUE THREAD

**Issue by danipolo** [visiblevc/wordpress-starter#118]
Hi,

Not an issue, just a question:

When do you plan to release the Part 4: Auto deploy your site on your server?

Looks awesome!

Regards

**Comment by karellm** [comment]
I don't plan on writing it any time soon. Your best bet is for @dsifford to document how he deploys his installs to production.

**Comment by dsifford** [comment]
See here: https://github.com/visiblevc/wordpress-starter/issues/68#issuecomment-309096255

**Comment by dsifford** [comment]
Of note: Kubernetes looks like a potentially nice way to deploy this, but I've never dove into it. It would probably be the route I'd go now if I didn't already do it the way described in the link above.

**Comment by danipolo** [comment]
Yes, it looks your deployment via scp it's maybe little bit basic for our needs. Move all to Kubernetes its something out of my posibilities right now (too much changes). I will check if there's something more organized. Thank you all!

**Comment by karellm** [comment]
@danipolo If you figure this one out, please share it back with us :)
