### ISSUE TITLE
Add DB_USER environment variable support

### ISSUE THREAD

**Issue by pragmaticivan** [visiblevc/wordpress-starter#119]
## Overview

- What's your problem about?
There's no option to use another USER other than `root`
- What is your operating system?
MacOS
- What is your docker version? `docker version`
17.09.0-ce

## Project structure

```
/wp-content
  /plugins
    /my-plugin
  /themes
    /my-theme
```

**Comment by craigedmunds** [comment]
It's hardcoded in the run script https://raw.githubusercontent.com/visiblevc/wordpress-starter/master/run.sh - assume there's a reason for it?

**Comment by dsifford** [comment]
No reason for it. Just figured it wasn't going to be something that would really matter and defaulting it to simply "root" would be easiest to remember if somebody was responsible for managing a number of different sites.

Adding the option to set the username sounds reasonable to me. Feel free to open a PR.
