### ISSUE TITLE
wp-content folder permission issues

### ISSUE THREAD

**Issue by vlkz** [visiblevc/wordpress-starter#12]
wp-content is `root:root`

The subfolders are `www-data:www-data`

When I go into `wp-content/` and `mkdir themes` I get access denied.

Any suggested solutions?

**Comment by karellm** [comment]
@vlkz Can you describe where you `mkdir themes` and what you are trying to achieve?

**Comment by vlkz** [comment]
@karellm I'm trying to begin developing a wordpress theme.

I clone this repo, cd into repo's folder, do ```docker-compose up```, wait for it finish.

Visit ```localhost:8080```, go through the wordpress setup.

From another terminal I cd to the repo's directory, a new folder has been created, ```wp-content```, so I cd into it, no ```themes``` folder exists so I try to create it with ```mkdir themes``` and that's where I run into the permission issues.

**Comment by karellm** [comment]
@vlkz I invite you to follow the [tutorial](https://visible.vc/engineering/docker-environment-for-wordpress/). If you are not familiar with Docker, it might be a slightly weird process. If you have questions about any step of the tutorial, please let me know.

**Comment by karellm** [comment]
Closing this, please reopen if you are having an issue with the tutorial.

**Comment by louisremi** [comment]
Since I began using wordpress-starter two weeks ago, I had the same problem as @vlkz: every time I restart the container, I need to change the permission of volumed files in wp-content before I can edit and save them.

I thought this was normal but it probably isn't. Why aren't the file permissions 664 instead of 644 [in run.sh](https://github.com/visiblevc/wordpress-starter/blob/master/run.sh#L120)? This way I can simply add myself to the `www-data` group, and start editing volumed with no permission changes.

Or have I missed something obvious in the tutorial?

**Comment by dsifford** [comment]
@louisremi Known annoyance. Has to do with the bootstrap user being `root`. I can fix when I get some time.

**Comment by dsifford** [comment]
The fix in the meantime is to just run `sudo chown -R $USER .` in the project root on your local machine after building the first time.

**Comment by louisremi** [comment]
Alright. Can you reopen this bug to make sure its taken care of at some point :-)

**Comment by louisremi** [comment]
Note that I need to use your workaround after each `docker-compose up`, not just after building the first time. A 664 permission on Wordpress files would allow me to use my workaround just once :-)

**Comment by andrewhavens** [comment]
FWIW I started using this project, following the instructions in the tutorial and readme, and have not run into any kind of permissions issues. I'm running this on my Mac. Maybe this bug has been fixed?

**Comment by carpnick** [comment]
I just hit this with the themes folder and the plugin folder.  It was being mounted as docker:staff.  The files could not be read by apache.  Using boot2docker.

Narrowed it down to this issue: https://github.com/boot2docker/boot2docker/issues/581

Which brought be to the following workaround(once container is built, inside container run):
```
usermod -u 1000 www-data
chown -R www-data:www-data .
```

This is making it so the mounted volumes and the user running apache are the same UID.  Was going to put in a PR for this when I got a second.  Just spent about 4-5 hours trying to get this to work on my end.

**Comment by dsifford** [comment]
@carpnick #97 addresses and fixes this problem. Just waiting on code review 🎉

**Comment by carpnick** [comment]
Thanks @dsifford .  Needed to understand what the heck was going on before I attempted a review.  Spent several hours understanding how your entire process was working, where docker/vbox/boot2docker all play together.  I am rather new to docker, so I had to do a big lift to get the understanding.
