### ISSUE TITLE
Deprecation warning - Warning: [local]plugin-name / local]theme-name

### ISSUE THREAD

**Issue by zulfeekar** [visiblevc/wordpress-starter#123]
## Deprecation warning.

Hi there, I have the latest version of visiblevc wordress-starter and I still get the deprecated warning. 

#Warning: [local]plugin-name has been deprecated and will be dropped in the next version.
#Warning: [local]theme-name has been deprecated and will be dropped in the next version.

- How can I fix this? 

thanks again for the wonderful starter kit :-)

![image](https://user-images.githubusercontent.com/1814993/34078402-006fd9a2-e31a-11e7-8f4b-44c00875283f.png)

**Comment by dsifford** [comment]
@zulfeekar You're likely using the `latest` tag which is a bit of a misnomer. Unless you manually remove the `latest` image and then re-pull, Docker will use the `latest` version from whenever you initially pulled the image for the first time perpetually. 

So, my recommendation to you is to not use `latest` and actually use whatever tag is the latest one. (currently, that's `0.17.0-php7.2`).

If, however, you still want to continue with `latest`, all you'll have to do is `docker image rm visiblevc/wordpress` and then re-run `docker-compose up`

**Comment by dsifford** [comment]
Also, when you do that, delete all instances of `[local]plugin-name` and `[local]theme-name` from your compose file because they will now begin to break your builds

**Comment by zulfeekar** [comment]
Hi, @dsifford thanks. Currently using  visiblevc/wordpress:0.16.0-php7.1 ..and no deprecation warning. Just wondering, keeping 0.16.0-php7.1 will be a problem in the future for continuous deployment?

**Comment by dsifford** [comment]
Nope, shouldn't be a problem. You're free to stay locked at an older version if you're fine with being locked at an older version of wp-cli on build. The old tags will exist forever in the docker registry.
