### ISSUE TITLE
Dumping the development db gives error: No such file or directory

### ISSUE THREAD

**Issue by MariusStuparu** [visiblevc/wordpress-starter#141]
Hello,

I have adapted (mostly, blatantly copied) the main files inside my project, and everything works fine (WP is up and running). But I get an error when trying to create a db dump:

`docker-compose exec wordpress /bin/bash 'wp db export /data --allow-root'`

gives this error:

`bin/bash: wp db export /data/ --allow-root: No such file or directory`

I have the `/[my-project]/data/` folder, and everything else is mostly the dafault.

I'm runnig Docker 18.05.0-ce-mac67 on MacOS 10.13.6

**Comment by dsifford** [comment]
Try adjusting your command to this and let me know if that works...

```
docker-compose exec wordpress /bin/bash -c 'wp db export /data --allow-root'
```

**Comment by MariusStuparu** [comment]
It was actually `docker-compose exec wordpress /bin/bash -c 'wp db export /data/mysqldump.sql --allow-root'` (the filename is needed). But it works now, thanks.

**Comment by dsifford** [comment]
Great. Glad you got it sorted out.

Of note, you shouldn't need `allow-root` with the lastest image unless explicitly running sudo.

**Comment by PabloDinella** [comment]
I think README should be updated :)

**Comment by dsifford** [comment]
PRs accepted
