### ISSUE TITLE
Working with local hostnames

### ISSUE THREAD

**Issue by keskistok** [visiblevc/wordpress-starter#153]
This is not really an issue. It's more of a general question. Im trying to figure out how to work with local hostnames when using this setup.

I have tried adding the IP address of the running wordpress container to my /etc/hosts file, but when trying to access the attached hostname I don't get any response.

Do you have any suggestions?

**Comment by signaleleven** [comment]
If you are using something similar to the example docker-compose, the container ports are exposed on the host.
You can put 127.0.0.1 in /etc/hosts, not the container IP, to test with hostnames.
