### ISSUE TITLE
Various build pipeline changes discussion

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#16]
(See #15 for the beginning of this conversation)

@karellm I'd be happy to collab on this if you'd like. Look over [my fork](https://github.com/dsifford/wordpress) and let me know what you think. 

It's also an [automated build](https://hub.docker.com/r/dsifford/wordpress/builds/) on Dockerhub

Short on time at the moment, but I'll chime in with a full description of what I changed later on.

**Comment by karellm** [comment]
Does file upload work in your fork? Because the app is inside a volume, it is impossible to set the proper permissions. I was curious if you found a solution to that issue?

**Comment by dsifford** [comment]
@karellm Not at the moment, but I think I know know why.. Giving it a shot now. I'll let you know.

**Comment by dsifford** [comment]
@karellm Yep... I figured it out.

See here for the fix: dsifford/wordpress@0ab80244c4a686de841c7fedd35c843112b490a2

**Comment by dsifford** [comment]
@karellm Actually, put a pin in that for now.. This works, but it's in the wrong direction.. I'll make the proper fix tomorrow sometime.

**Comment by dsifford** [comment]
@karellm Done. dsifford/wordpress@18be581c7f4b253c0341155566736d3604b4b417

also check out the latest commit -- added an automatic method for replacing urls on build.

**Comment by dsifford** [comment]
@karellm I feel like I'm yappin' your ear off, but I just wanted to mention that I just did a huuuuuuuge build script refactor in favor of wp-cli. This repo uses mysql directly, which is fine, but I figured that if we already have wp-cli installed, we might as well take advantage of it...

Check it out here: dsifford/wordpress@b7c91cc8f12b349fe82f412d3b3a3264c62ec1c9

**Comment by karellm** [comment]
@dsifford No please keep it coming, I just have limited bandwidth these days. Would you be interested in collaborating directly here? Internally at Visible we rely heavily on PRs to have discussions and review code. I haven't done it before in this repo since I was the only contributor but would love to switch to that flow.

I always find silly to spread the OS effort, especially on projects that close from one another :) And your contribution and ideas are highly valued!

**Comment by dsifford** [comment]
@karellm Sure. Although, my fork is a bit different than this (my scripts folder only has 3 files since I combined a few of the scripts you have). How did you want me to PR the changes?

The last thing I need to work on before I'll be satisfied enough to call it done is I need to build in a check to grab IP addresses from people running docker through docker-machine. That way the URLs can be changed to match automatically (based on an optional environment variable).. It works for me as-is right now, but I'm on a linux machine so my IP stays the same always.

**Comment by karellm** [comment]
@dsifford The issue with a single script is that in development, you can't switch DB anymore. Sure you can kill the containers and volumes and start new ones but I don't think it is ideal.

For the machine IP address, I personally forward VBox ports and use `localhost:8080` on my host machine. I don't think the project should include OS specific code, plus it is just a matter of running something like that: `VBoxManage controlvm default natpf1 "tcp8080,tcp,127.0.0.1,8080,,8080"`.

For the PR changes, I would do them one at a time. We can discuss one change (like should we merge scripts), decide what is the best course of action and then make a PR for it. wdyt?

**Comment by dsifford** [comment]
@karellm To address your comments in order:

> The issue with a single script is that in development, you can't switch DB anymore. 

Yes you can. All you need to do is drop a new`.sql` file into the data folder and then run `docker exec -it $(docker ps -lq) /bin/bash -c wp db import --allow-root`

> I don't think the project should include OS specific code

I agree. The goal was to be able for the build to detect the user's IP during build and then replace the URLs from the data backup automatically. Definitely a luxury, so it's not a huge deal. Glad to hear there is any easy way to forward VBox ports.

> For the PR changes, I would do them one at a time. 

Sounds good. I'll start with the ones that handle the two open issues first later on this evening or tomorrow :beers:

**Comment by dsifford** [comment]
@karellm So, I'll be honest -- I'm far too lazy to retroactively apply each of the changes one-by-one. 

I'm going to create a PR now including the big master change to `run.sh` and adjust the Dockerfile and we can discuss line by line there. (Hope that's okay).

**Comment by karellm** [comment]
Sounds good to me!

**Comment by karellm** [comment]
I think we addressed most of what's in here. Closing this but feel free to open new tickets on specific features.

**Comment by blackwood** [comment]
Wonder if this: `VBoxManage controlvm vm-name natpf1 "tcp8080,tcp,127.0.0.1,8080,,8080"` should be in the README? Spent a couple minutes scratching my head as to why the "two-line get started" in the docs was loading the site, but not any theme assets from `localhost:8080`

**Comment by karellm** [comment]
@blackwood I added it. Thanks for the feedback!
