### ISSUE TITLE
Volume mapping for wordpress /app

### ISSUE THREAD

**Issue by geeksupport1** [visiblevc/wordpress-starter#161]
Thanks for sharing this.

PLEASE READ THIS BEFORE POSTING AN ISSUE!

This is a template to make sure you provide us with all the information we will be to help you out. Please take the time to fill detailed issues, it will be faster for us to provide solutions! In the following sections, you should replace the content with your own. The content that is there is just presented as an example.

## Overview

- What's your problem about?
cannot see Volume mapping of wp-content

The docker-compose file says ./data. but nothing is in the ./data directory.

Upon closer inspection, the WORKDIR is set to /app

- What is your operating system?
windows 10 Pro WSL

docker daemon in WSL working.

- What is your docker version? `docker version`
19.03.4
## `docker-compose.yml`
https://github.com/visiblevc/wordpress-starter

=========================================

I later discovered the examples directory contains the updated docker-compose.yml file.

However, wp-content is not mapped to host, so files in wp-content will not be saved upon container crash.

**Comment by dsifford** [comment]
Having trouble understanding exactly what the issue you're having with this project is, but...

> However, wp-content is not mapped to host, so files in wp-content will not be saved upon container crash.

`wp-content` isn't supposed to be volumed. That's the point of this setup. It keeps the builds ephemeral. The only thing you should volume are things that need to survive teardowns.. So, generally, speaking... 
- `wp-content/uploads` (optionally)
- `wp-content/themes/<the-theme-you're-developing>` (optionally)
- `wp-content/plugins/<the-plugin-you're-developing>` (optionally)
