### ISSUE TITLE
How to prevent files + database from being purged?

### ISSUE THREAD

**Issue by simplenotezy** [visiblevc/wordpress-starter#174]
As it seems from the looks of the issues, themes/plugins/files (and perhaps also database?) get's purges on up/down.

How can I disable this? I'd like to keep my files and database intact, even after a reboot or up/down.

**Comment by dsifford** [comment]
Use `docker-compose stop` and not `docker-compose down`.

**Comment by simplenotezy** [comment]
Thanks. I also noticed the https://visible.vc/engineering/docker-environment-for-wordpress/ which seems like a good solution
