### ISSUE TITLE
Make this an automated build on Dockerhub

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#19]
Happy to help if you're not sure how to go about doing it.

**Comment by dsifford** [comment]
@karellm Thoughts on this? This is the last thing I'll need before depreciating my fork

**Comment by karellm** [comment]
I want to but our we are waiting to regain access to our Docker Hub account (reset password does not work). Why do you need it?

**Comment by dsifford** [comment]
I prefer that because it ensures that I'll always have the latest version of the image and negates the need for anything other than a `docker-compose.yml` file.

**Comment by dsifford** [comment]
@karellm On sort of this same topic, what are your thoughts on changing the name of this repo from `visiblevc/wordpress-starter` to `visibilevc/wordpress`?

Two reasons: 
1. Less verbose and easier to type into a from-scratch compose file
2. I think this is quickly becoming more than just a "starter" orchestration! :metal: 

Let me know your thoughts. 

Also, any updates on getting into your dockerhub account?

**Comment by karellm** [comment]
I don't like project that name themselves after another OS project. It is not a fork of wordpress, so I don't think it should be named `wordpress`. The image is named wordpress but that's clear by the nature of Docker and images.

As to automated builds, I looked into them and can't see a reason for them. With our current flow, I disagree that master should always result in a build (keep in mind this is OS, used by people). Controlling releases is important and master might be unstable. To support automated builds, we would need a better flow making sure master is always safe and it honestly feels like a total overkill. Deploying an image takes no time and won't happen often.

**Comment by dsifford** [comment]
@karellm I was imagining that after we get through the meat of the recent changes, we could create release branches. 

Once we're ready to release a new version, just create a branch called with the semver name and have those branches build automatically. You don't have to automatic build master if you don't want to. Each new build would also effectively be tagged the branch name (so, kills two birds).. Eg. if there are three branches `master`, `v0.1.0`, and `v1.0.0`, that would result in these images:
- `visiblevc/wordpress-starter:0.1.0`
- `visiblevc/wordpress-starter:1.0.0` and `visiblevc/wordpress-starter:latest`

Also, I'm not 100% certain, but I do think automated builds are higher in rank when searched using dockerhub or docker cli.

Just food for thought.

**Comment by karellm** [comment]
@dsifford Since we are maintaining a `CHANGELOG` (there is already manual work involved) and based on the volumne of builds, I still think automated builds are necessary. I will close this for now.

**Comment by dsifford** [comment]
No prob. I keep a fork of this as an automated build for my own convenience so my needs are covered.
