### ISSUE TITLE
gulp `clean` task should also remove generated templates

### ISSUE THREAD

**Issue by e2** [visiblevc/wordpress-starter#25]
This would help see which templates are generated (copied by gulp) vs not.

**Comment by karellm** [comment]
Can you provide some more details? Your description is pretty cryptic, we are not in your head so when you submit tickets, please make the effort to ensure you will be understood. You can provide the current behaviour, the expected behaviour or even better a PR.

**Comment by e2** [comment]
Yes, sorry. What I had in my head was the wordpress-starter tutorial/docs about asset handling.

I meant that the `clean` tasks just removes the `dist files`. But files such as `index.php` are supposed to be copied from `assets/templates` into the theme dir. Since they are "generated" (copied by `compile-templates` gulp task), `clean` should remove them as well, right?

**Comment by e2** [comment]
https://github.com/visiblevc/wordpress-starter/pull/26
