### ISSUE TITLE
Working with WP plugins

### ISSUE THREAD

**Issue by bluespore** [visiblevc/wordpress-starter#29]
Is there an easy way to automatically activate plugins? 

Main issue is when ever I try to run wp-cli commands on the machine with `command:` in the `docker-compose.yml` it runs before everything is good to go.

So if I was to add `command: wp plugin activate --all` I  get the following output:
```bash
wordpress_1 | Error: This does not seem to be a WordPress install.
wordpress_1 | Pass --path=`path/to/wordpress` or run `wp core download`.
```

I might have missed something here, so happy for some guidance.

**Comment by karellm** [comment]
If you look at the [format](https://github.com/visiblevc/wordpress-starter#the-docker-environment) for the `docker-compose.yml`, there is an ENV variable named `PLUGINS`. Simply add your plugins there and they will be automatically installed.

If you want to install a specific plugin after the fact. Read [section 4 of this article](https://visible.vc/engineering/docker-environment-for-wordpress/).

**Comment by bluespore** [comment]
@karellm The key here is that I want to activate all plugins from the `docker-compose.yml` `command` argument. Your article only describes how to `exec` wp-cli commands after it's already running. 

Apologies if I didn't pick up on something between the lines here.

**Comment by dsifford** [comment]
@bluespore this would require a modification of the `run.sh` file. Fork the repo and add `--activate` to [this line](https://github.com/visiblevc/wordpress-starter/blob/master/run.sh#L151)
