### ISSUE TITLE
None writeable permissions with chown /app/wp-content

### ISSUE THREAD

**Issue by motleydev** [visiblevc/wordpress-starter#3]
For some reason Wordpress was still asking for ftp permission to install plugins, when I modified the Dockerfile to chown /app instead it was ok. Any idea why?

**Comment by karellm** [comment]
@motleydev Well your are not technically supposed to install plugins via wordpress. To make the project and environment reproducible, it is better to use the `data/plugins` file. You can see this documented [here](https://visible.vc/engineering/docker-environment-for-wordpress/).

**Comment by motleydev** [comment]
ok, I get that. I'm having an issue with the image not downloading a fresh copy of wordpress. I tried deleting the old image it pulled but it always downloads an older version of WP. How can I get around that?

**Comment by karellm** [comment]
@motleydev It is indeed a problem. I opened a ticket #5
