### ISSUE TITLE
Is it possible to run modified version of run.sh on starting container?

### ISSUE THREAD

**Issue by neelakansha85** [visiblevc/wordpress-starter#33]
Hi,

This is really good and I learning to make use of docker. I am trying to use this for my plugin development workflow. I usually work with wordpress multisite and so was trying to see if there is a way to override the default run.sh file while executes while starting the container. 

I have tried using the `command:` in docker-compose.yml but no luck. Or is there a way you could create a postrun.sh file which by default is empty but a user can fill it up with all custom commands he wishes to execute after the container in up and running. 

I also tried running the `docker exec $(docker ps -lq) /bin/bash -c "wp core multisite-convert --allow-root"` however that sometimes works and sometimes doesn't really respond (not sure why). I use Docker for Mac. 

Thanks,
Neel

**Comment by karellm** [comment]
@neelakansha85 I didn't feel like implementing the postrun.sh but I just added multisites in `0.7.0`. To enable it, add `MULTISITE: 'true'` to your Dockerfile ENV variables.

**Comment by dsifford** [comment]
@neelakansha85 Future reference: you should be able to add a command which executes a separate shell script, assuming you also add that script as a volume.

**Comment by neelakansha85** [comment]
Thanks @karellm and @dsifford for the suggestion. For now I have modified the run.sh script and am running it using local dockerfile. I will try mounting it as a volume it's just that I was trying to find a way in which I can have the file automatically running on starting the container over manually triggering it.

**Comment by dsifford** [comment]
When using a `command` in the compose file, it is a "one or the other" operation. The command that you add is not composable over top of the default command. 

So in your case, if you need something specific along with the rest of the default commands, it's probably best to just fork this repo and modify the source rather then adding a separate command.

**Comment by neelakansha85** [comment]
Yeah, agreed. I forked your repo https://github.com/neelakansha85/wordpress-starter and modified it. I do want to comment you for the great work your team has done here. Since it definitely helps me a lot.

**Comment by dsifford** [comment]
All credit goes to @karellm ... I'm just a lowly contributor! 😃

**Comment by karellm** [comment]
@dsifford Lowly contributor? This repo wouldn't be anywhere close to where it is without you! I would be happy to actually give you contributor rights on the repo if you want them.

**Comment by dsifford** [comment]
@karellm You're too kind, really.

Re: Contributor access - Totally up to you. That's a whole lot of power! 😃
