### ISSUE TITLE
"Stylesheet is missing" on installing existing theme.

### ISSUE THREAD

**Issue by jaronoff** [visiblevc/wordpress-starter#35]
Hello!
I am following the instructions here: https://visible.vc/engineering/docker-environment-for-wordpress/

and I have run into an issue where I'm installing an existing theme, i've pointed to said theme in the docker compose yml file, and I go to start my instance. It has the theme in there, but I get a "stylesheet is missing" in the description and it's in the "Broken Themes" section.

<img width="1032" alt="manage_themes_ _wordpress_ _wordpress" src="https://cloud.githubusercontent.com/assets/433966/17708656/eea484fc-63b3-11e6-8f7c-137645808377.png">

I'm somewhat of a noob at this, so I'm sure it might just be something elementary. Any help you could give would be greatly appreciated.

Thanks!
Josh

**Comment by dsifford** [comment]
@jaronoff Can you share your `docker-compose.yml` file?

**Comment by jaronoff** [comment]
I actually figured it out. I ended up just doing a complete fresh install, and walking through it again. I got it working.

Thanks!

**Comment by dsifford** [comment]
Sweet! Feel free to chime back if you run into any other issues. 👍

**Comment by leiluspocus** [comment]
Hi,

I'm experiencing the same error. What do you mean by "I ended up doing a complete fresh install" ? You followed this tutorial ( https://visible.vc/engineering/docker-environment-for-wordpress/ ) again ? 

Thank you !

**Comment by dsifford** [comment]
Hi @leiluspocus 

Can you paste over your compose file and any error messages that you might have from the build here?

**Comment by leiluspocus** [comment]
Hi @dsifford  

Thanks for the prompt reply. 

This is my compose file : 

`version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wp-content/themes/mythemename:/app/wp-content/themes/mythemename
    environment:
      DB_NAME: wordpress
      DB_PASS: root
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
`

Please note that ./wp-content/themes/mythemename is a symbolic link to a Git repository I have in my local environment. mythemename is a custom theme, our style.css file is located in a special folder (in the same theme) but there is also an empty style.css file at the root of the theme.

**Comment by dsifford** [comment]
This configuration assumes you have a folder called `wp-content` at the top level of your project directory. Is that true?

Also, I'm fairly certain volumed files cannot be symlinks. Can you try copying it over to your project directory instead?

Future reference: surround your code like this for better code rendering in github comments:

![image](https://cloud.githubusercontent.com/assets/5240018/19529292/4788839a-95fd-11e6-8197-3a8c2d925751.png)

**Comment by leiluspocus** [comment]
Thank you for the YML tip :) 

> This configuration assumes you have a folder called wp-content at the top level of your project directory. Is that true?
Yes, I do. 

>  Can you try copying it over to your project directory instead?
I also tried, same result.

**Comment by dsifford** [comment]
@leiluspocus Do you have a repo that I can pull and test to see if I can recreate your issue?

Also, were there any errors logged? (after running `docker-compose up -d` you can view the logs by running `docker-compose logs wordpress` -- Or, if you're like me, you can do it all in one go by using this command: `docker-compose up -d && docker-compose logs -f wordpress`.

Thanks

**Comment by leiluspocus** [comment]
Hi @dsifford 

I don't have a test repo unfortunately. However, I noticed the following error in the logs : 

```
wordpress_1  | ==> Checking for orphaned themes
wordpress_1  | Error: No themes deleted.
wordpress_1  |   -> 'braxton' no longer needed. Pruning ✘
wordpress_1  |   -> 'twentyfifteen' no longer needed. Pruning ✓
wordpress_1  | Error: No themes deleted.
wordpress_1  |   -> 'twentyseventeen' no longer needed. Pruning ✘
```

Could it be linked ?

**Comment by leiluspocus** [comment]
Ah actually, I forgot to add this line in my docker-compose.yml file : 

```
      THEMES: >-
        [local]braxton
```

Theme was succesfully mounted as it says in the logs : 
```
wordpress_1  | ==> Checking themes
wordpress_1  |   -> (1/1) 'braxton' listed as a local volume. SKIPPING... 
wordpress_1  | ==> Checking for orphaned themes
wordpress_1  |   -> 'twentyfifteen' no longer needed. Pruning ✓
wordpress_1  |   -> 'twentyseventeen' no longer needed. Pruning Error: No themes deleted.
wordpress_1  | ✘
wordpress_1  |   -> 'twentysixteen' no longer needed. Pruning ✓
wordpress_1  | ==> Checking plugins
wordpress_1  |   -> No plugin dependencies listed 
wordpress_1  | ==> Checking for orphaned plugins
wordpress_1  |   -> 'akismet' no longer needed. Pruning... ✓
wordpress_1  |   -> 'hello' no longer needed. Pruning... ✓
wordpress_1  | ==> Finalizing
wordpress_1  |   -> Generating .htaccess file ✓
wordpress_1  |   -> Adjusting file permissions ✓
``` 

However, I still have the same error.

**Comment by leiluspocus** [comment]
Well, my bad, the theme folder was empty ... 😳  

To the next one who might have this kind of issue : 
- Double-check that the environment variable is defined in the docker-compose.yml file so that theme can be mounted
```
  THEMES: >-
        [local]<your_Theme>
```
- Make sure your theme folder is correct 😓  

Such a great work guys, thank you !
