### ISSUE TITLE
Dockerfile conflict + outdated(?) shell script

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#4]
Hi there. 

First of all, excellent base image! I read your associated blog post and the way you have this set up is extremely clever.

Some issues I'm having are the following...

1. The `install-plugins` shell script you have in this repository is outdated and does not work. I think [this line](https://github.com/visiblevc/wordpress-starter/blob/master/scripts/install-plugins.sh#L9) needs to be updated to this....

```sh
curl -LOk# https://downloads.wordpress.org/plugin/${plugin}.zip
```

2. Is the Dockerfile in this repo the same as the one used in your dockerhub image? The reason I ask is because I can cleanly install wordpress using your dockerhub image, but I can not do the same if I fork this repo, and change the `image: visiblecv/wordpress` line in the docker-compose.yml file to `build: .`. Could this an error on my end?

Thanks for the help!

**Comment by karellm** [comment]
@dsifford Thanks for reporting this, I will investigate over the weekend.

**Comment by karellm** [comment]
@dsifford I will close this for now. I pushed the plugin fix.
