### ISSUE TITLE
Export command doesn't work

### ISSUE THREAD

**Issue by carloscasalar** [visiblevc/wordpress-starter#41]
Export command fails for me:

```bash
$ docker-compose run wordpress wp db export /data --allow-root
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```
If I run a `docker run` inside wordpress container then it works:
```bash
$ docker exec -it wordpress_wordpress_1 wp db export /data/wordpress.sql --allow-root
```

For instance, I've tried to do a `ls -l` with this two ways with different results:
```bash
$ docker-compose run wordpress ls -l
total 24
-rw-r--r-- 1 root root  1202 Jul  8  2015 index.php
-rw-r--r-- 1 root root 12586 Jul  8  2015 logo.png
drwxr-xr-x 4 root root  4096 Sep 24 16:52 wp-content

$ docker exec -it wordpress_wordpress_1 ls -l
total 208
-rw-r--r--  1 www-data www-data   418 Sep 24 11:05 index.php
-rw-r--r--  1 www-data www-data 19935 Sep 24 11:05 license.txt
-rw-r--r--  1 www-data www-data 12586 Jul  8  2015 logo.png
-rw-r--r--  1 www-data www-data  7344 Sep 24 11:05 readme.html
-rw-r--r--  1 www-data www-data  5456 Sep 24 11:05 wp-activate.php
drwxr-xr-x  9 www-data www-data  4096 Sep 24 11:05 wp-admin
-rw-r--r--  1 www-data www-data   364 Sep 24 11:05 wp-blog-header.php
-rw-r--r--  1 www-data www-data   413 Sep 24 15:42 wp-cli.yml
-rw-r--r--  1 www-data www-data  1477 Sep 24 11:05 wp-comments-post.php
-rw-r--r--  1 www-data www-data  2853 Sep 24 11:05 wp-config-sample.php
-rw-r--r--  1 www-data www-data  1625 Sep 24 15:42 wp-config.php
drwxr-xr-x  7 www-data www-data  4096 Sep 24 16:13 wp-content
-rw-r--r--  1 www-data www-data  3286 Sep 24 11:05 wp-cron.php
drwxr-xr-x 17 www-data www-data 12288 Sep 24 11:05 wp-includes
-rw-r--r--  1 www-data www-data  2382 Sep 24 11:05 wp-links-opml.php
-rw-r--r--  1 www-data www-data  3353 Sep 24 11:05 wp-load.php
-rw-r--r--  1 www-data www-data 34057 Sep 24 11:05 wp-login.php
-rw-r--r--  1 www-data www-data  7786 Sep 24 11:05 wp-mail.php
-rw-r--r--  1 www-data www-data 13920 Sep 24 11:05 wp-settings.php
-rw-r--r--  1 www-data www-data 29890 Sep 24 11:05 wp-signup.php
-rw-r--r--  1 www-data www-data  4035 Sep 24 11:05 wp-trackback.php
-rw-r--r--  1 www-data www-data  3064 Sep 24 11:05 xmlrpc.php
```

I'm running docker for mac 1.12.1.

My `docker-compose.yml` is like the one in f7ae79e but with an additional phpMyadmin container.

**Comment by dsifford** [comment]
@carloscasalar  

You shouldn't use `docker-compose run` in this scenario for the following reason (this is pulled right from their docs)

> Commands you use with run start in new containers with the same configuration as defined by the service’ configuration. This means the container has the same volumes, links, as defined in the configuration file. There two differences though. 

> First, the command passed by run overrides the command defined in the service configuration. For example, if the web service configuration is started with bash, then docker-compose run web python app.py overrides it with python app.py.

> The second difference is the docker-compose run command does not create any of the ports specified in the service configuration. This prevents the port collisions with already open ports. If you do want the service’s ports created and mapped to the host, specify the --service-ports flag:

Because we bootstrap the wordpress install after the service is built, `run` commands won't work. You need to run `docker exec` commands...

I have this alias set in my `.bashrc` because I find myself always wanting to open an interactive session in containers: 

```sh
# Open an interactive bash session in container N (counting from top)
dx () {
    docker exec -it $(docker ps -q -n=$1 | tail -n 1) /bin/bash -c "export TERM=xterm; exec bash"
}
````

if you want to simply run one-off commands, I'd recommend using the npm script workflow we describe in the documentation:

Assuming you have the following script added to your `package.json`....

```json
"scripts": {
    "wp": "wpcmd() { docker exec $(docker ps -lq) /bin/bash -c \"sudo -u www-data wp $(echo $@)\"; };wpcmd "
  },
```

All you'd need to do is run `npm run wp db export /data` 


Hope that helps 👍

**Comment by carloscasalar** [comment]
I like the npm way. And I love the `.bashrc` tip. Thanks it helps!

However, be aware of this line in README.md: https://github.com/visiblevc/wordpress-starter/blame/f7ae79e4dd28efa50c9f9d1d47b7570e1d4dc44a/README.md#L124 is what has led me to misunderstanding.

**Comment by dsifford** [comment]
@carloscasalar Thanks for pointing that out. Will fix on the next update 👍
