### ISSUE TITLE
404 isn't working 

### ISSUE THREAD

**Issue by Wardormeur** [visiblevc/wordpress-starter#42]
Hi,
I believe it comes from the apache conf that when using permalink as plain, the 404 page isn't caught by wp, but by apache.
Changing to another format (without ?) seems to work tho.

**Comment by dsifford** [comment]
Not sure I'm following what you're saying. Can you elaborate?

**Comment by Wardormeur** [comment]
If you go to any page while using the default configuration for pemalinks ("/?p=") the 404 page from WP is not triggered when using a random path ("/qsd") while i believe it should ?

**Comment by dsifford** [comment]
What page shows up instead? Just the standard "page cannot be displayed" page, I assume?

htaccess probably needs to be adjusted if that's the case.

**Comment by Wardormeur** [comment]
It was the default rendering from apache's HTTP error (whie page + error code).
Though, I have no idea if WP does a "catchall" for 404 and if the catchall behavior changes when changing the slug format

**Comment by dsifford** [comment]
@Wardormeur Which theme are you referring to?

**Comment by Wardormeur** [comment]
the default one, twentySixteen

**Comment by dsifford** [comment]
Twentysixteen should be showing this page: https://github.com/WordPress/twentysixteen/blob/master/404.php

I'm not able to reproduce your issue. Thoughts @karellm ?

**Comment by karellm** [comment]
@dsifford If I follow the getting started steps and visit a random page `localhost:8080/foo` I indeed end up on the apache 404:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3O3u2W172R2n313o3L3m/Image%202016-10-26%20at%209.23.17%20AM.png?v=47929168)

I will investigate soon

**Comment by dsifford** [comment]
@Wardormeur You're right! I was just able to reproduce. I know what's wrong. I'll push a fix out in the next 20-30 minutes

@karellm I'm going to push the fix directly to `master`. I'll update the CHANGELOG and do a patch bump to the semver number. 👍

**Comment by dsifford** [comment]
@karellm Fixed. 

This still needs to be built on dockerhub. 

Also, I'm not sure how this will work out in instances where users are importing a database with rewrite rules already set. I'll likely have to add a check somewhere to prevent this from overwriting permalink rules.

**Comment by karellm** [comment]
@dsifford Couple things:

1/ Thanks for the fix!
2/ I prefer we never push to master but always make PRs, even for small changes. I grew accustomed with our team to review everything and I think it is a good habit to have when collaborating on projects
3/ Automated builds: I recall now why I didn't set it up. It require admin access to our github account, and for security reason I'm not willing to give it to Docker. There is an option to only give public access but it doesn't allow created automated builds from private organizations. As a workaround, I gave your write access to the image so you can now push directly. You can find the instructions [here](https://github.com/visiblevc/wordpress-starter/wiki/Development).

**Comment by dsifford** [comment]
@karellm Noted. My bad!
