### ISSUE TITLE
docker-compose up doesn't finish.

### ISSUE THREAD

**Issue by RyosukeTakahashi** [visiblevc/wordpress-starter#49]
I did just what I was told to, cloned git and did docker-compose up.
I didn't touch docker-compose.yml at all.
Lots of message started appearing and it goes to like below.

...
wordpress_1  | => Removing unneeded themes... Done!
wordpress_1  | => Installing needed themes... Done!
wordpress_1  | 	=======================================
wordpress_1  | 	   WordPress Configuration Complete!
wordpress_1  | 	=======================================

and it just stops from then.
I waited for like an hour but nothing happens.
Tried to open localhost:8000 but of course, nothing opens.

I did it at both windows10 and OSX El Capitain and stops at the same position.
Is it just me?

**Comment by dsifford** [comment]
That looks finished to me. Can you tell me what you expected to happen?

**Comment by RyosukeTakahashi** [comment]
My huge apology, it was finished. It was my nooby mistake.
I was trying to access localhost:8000 instead of localhost:8080. So embarrassing...

I managed to see the page with the default wordpress theme using the default docker-compose.yml.
But I don't know the username and password to get in to the dashboard. 
As far as I can tell, cannot find it in the README.md .

Or should I import an database from an existing website?
Sorry for questioning this in the same issue.

**Comment by RyosukeTakahashi** [comment]
Sorry i got it. The username and password are both root.

**Comment by dsifford** [comment]
No problem. Glad you were able to get it working. 👍
