### ISSUE TITLE
Wordpress not installed?

### ISSUE THREAD

**Issue by benedict-w** [visiblevc/wordpress-starter#54]
I'm new to Docker, so apologies if there is something I am doing wrong / stupid! I really like the look of the docker setup you have here but I seem to get errors with installing WordPress

![screenshot 2016-11-29 14 56 23](https://cloud.githubusercontent.com/assets/1303610/20714486/1280baa2-b644-11e6-8508-926a10500bbf.png)

I've deleted the image and tried a few times now, with the same result.

**Comment by dsifford** [comment]
@benedict-w Can you verify how you are running this image? What command are you using exactly? Also, mind sharing your `docker-compose.yml` file?

**Comment by dsifford** [comment]
@benedict-w Marking this as resolved since I haven't heard back from you.
