### ISSUE TITLE
Development or productive image?

### ISSUE THREAD

**Issue by saschalalala** [visiblevc/wordpress-starter#6]
Hey there, I read your wordpress development blog post and set up this environment on my box.

I am quite happy with it (There are some possible tweaks in the scripts that I will look into later) but there is one thing that bugs me. In my comprehension, this is clearly an image with development in mind, not productive usage. So, for security/privacy reasons, I would (and did it here) only open the ports on my local machine, like

```
wordpress:
  ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
``` 
and
```
mysql:
  ports:
    - 127.0.0.1:3306:3306
```
because, by default having mysql running on default port with root:root authentication makes me feel sick. 

I think, in order to have docker images that can be used for developments "as is" they should be as closed down as possible, if one needs more, they need to configure it explicitly (Can be mentioned in the documentation, though).

**Comment by karellm** [comment]
The Docker image and setup is definitely intended for local development, so security was not even a concern. We started working on a deploy flow with production images via Docker but it is not ready yet (and don't know when it will be).

That said, I don't understand your concern. Unless your development machine is accessible from the network, how could people even access it?

Also note that what you are refering to is a Docker Compose config, you can change it if you feel better having a different MySQL password. You can even have run services on different ports.

**Comment by saschalalala** [comment]
Well, I know that I can change all these settings on my own. I just believe that providing default configs that are as secure as possible is a good idea in general. My development workstation is a laptop, so I am working on many different places (open wifi, freifunk, eduroam, work …) and I usually have a firewall (firewalld) running in Fedora23, all ports closed. Docker uses iptables to provide network interaction between running containers etc, so it "bypasses" my firewall by design (which is okay, as long as I am aware of it).

Of course, it is no problem for me to configure the yml file for my needs, but having a secure default configuration is just good practice. You can see what can happen otherwise when you have a look at the mongodb problems this year. I am also aware that providing dockerfiles this is in no way comparable to an open source database project like mongodb.

Too many people use default settings and just don't care.

**Comment by karellm** [comment]
@saschalalala I invite you to make a PR, I will definitely merge one providing higher security standards.

**Comment by karellm** [comment]
Done in `master` for mysql.
