### ISSUE TITLE
`docker-compose up` fails

### ISSUE THREAD

**Issue by stefanfrede** [visiblevc/wordpress-starter#60]
## Overview

- What's your problem about?

Initial `docker-compose up` fails with error.

- What is your operating system?

`macOS Sierra 10.12.1 (16B2555)`

- What is your docker version?

`Docker version 1.12.3, build 6b644ec`

## Getting started

```
# copy the files
git clone https://github.com/visiblevc/wordpress-starter.git
rm -rf .git Dockerfile run.sh README.md CHANGELOG.md ISSUE_TEMPLATE.md

# start the website at localhost:8080
docker-compose up
```

## `docker-compose up` output

```
Pulling wordpress (visiblevc/wordpress:php7.0)...
Pulling repository docker.io/visiblevc/wordpress
ERROR: Tag php7.0 not found in repository docker.io/visiblevc/wordpress
```

**Comment by karellm** [comment]
@stefanfrede There was a typo in the `docker-compose.yml`. The tag should not be `php7.0` but `latest`. You can find all the available tags in the README in case you want a specific php version.
