### ISSUE TITLE
Default Theme + Rest API issue

### ISSUE THREAD

**Issue by lorcanfurey** [visiblevc/wordpress-starter#62]
Hi, great starter by the way! 👍 

Just encountering a couple of issues;

1) Is there anyway to make the local test theme (mounted as a volume) set as the active theme by default? On my docker-compose.yml file, I have a local theme (**metro-creativex**) set but when docker-compose finishes, the default theme is **twentyseventeen**
2) I've indicated **rest-api** as a default plugin, but in the plugin checking part, the restful package also gets pulled in which causes a Composer error (see below)

Even just a nudge in the right direction would be helpful, thanks!

docker-compose.yml
```
version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest-php7.0
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data # Required if importing an existing database
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./metro-creativex:/app/wp-content/themes/metro-creativex   # Theme development
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      PLUGINS: >-
        [rest-api]https://downloads.wordpress.org/plugin/rest-api.2.0-beta15.zip,
      THEMES: >-
        [local]metro-creativex,
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data:
```

run.sh output:
```
===============================================================================
                         Begin WordPress Installation
===============================================================================
==> Installing WordPress
  -> Downloading... ✓
==> Waiting for MySQL to initialize...
  ->  mysqld is alive
==> Configuring WordPress
  -> Generating wp-config.php file... ✓
==> Checking database
  -> Creating database wordpress ✓
  -> No database backup found. Initializing new database ✓
==> Checking for multisite
  -> Multisite not found. SKIPPING...
==> Checking themes
  -> (1/1) 'metro-creativex' listed as a local volume. SKIPPING...
==> Checking for orphaned themes
  -> 'twentyfifteen' no longer needed. Pruning ✓
Error: No themes deleted.
  -> 'twentyseventeen' no longer needed. Pruning ✘
  -> 'twentysixteen' no longer needed. Pruning ✓
==> Checking plugins
  -> (1/1) 'rest-api' not found. Installing... ✓
  -> (1.5/1) Installing 'restful' WP-CLI package...
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126
✘
==> Checking for orphaned plugins
  -> 'akismet' no longer needed. Pruning... ✓
  -> 'hello' no longer needed. Pruning... ✓
==> Finalizing
  -> Generating .htaccess file ✓
  -> Adjusting file permissions ✓
===============================================================================
                       WordPress Configuration Complete!
===============================================================================
[Wed Dec 07 19:24:44.984603 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.0.13 configured -- resuming normal operations
[Wed Dec 07 19:24:44.984671 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by dsifford** [comment]
@lorcanfurey Ah, I see.. You have the theme locally downloaded, but are not importing a database from a site that has that theme enabled already. You're right, the theme would not be activated.

Let me look into this tomorrow and see if I can fix.

The other issues are being handled as well. We just overhauled and split into the two Dockerfiles so there's likely going to be a small period of bugfixes.

**Comment by dsifford** [comment]
Actually @karellm how do you think we should go about this?

Simply activating a theme if it's listed as a local volume will be less than ideal in most scenarios because most users who have local themes have them as a child of an existing theme. Activating all `[local]` themes will (50% of the time) cause the parent theme to be activated.

I think the current approach will lead to less headaches for a majority of users.

**Comment by dsifford** [comment]
@lorcanfurey try this...
1. Delete your local `metro-creativex` directory (but keep it listed as a volume).
2. Remove `[local]` from the theme in the `THEMES` env variable.
3. Build

This should download the theme to the directory in the container (and thus locally), and you should have the same effect.

Let me know

**Comment by lorcanfurey** [comment]
That worked, thanks!
Knowing that the current setup is for child theme dev is helpful too 👍
