### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mvasin** [visiblevc/wordpress-starter#65]
Hi,

where is Dockerfile? I can't see it neither in this repository nor on the [docker hub](https://hub.docker.com/r/visiblevc/wordpress/). It's no good to pull and install images when you don't know what's inside (= didn't compile it yourself).

**Comment by dsifford** [comment]
The php7.0 Dockerfile is in the php7.0 folder and the php5.6 Dockerfile is in the php5.6 folder.
