### ISSUE TITLE
Making it easier to tweak php.ini

### ISSUE THREAD

**Issue by louisremi** [visiblevc/wordpress-starter#67]
Hi guys, and thanks a lot for this project! I hadn't done WordPress development for some years and it seems you brought a bit of sanity to this old world 👍 

I needed to adjust some variables in php.ini to increase upload size on my website. I tried to modify the dockerfile both in the `php5.6` and `php7.0` directories, but that didn't work. I googled my problem and found a comment in a separate project that helped me a lot: https://github.com/docker-library/wordpress/issues/10#issuecomment-66906071

I figured it could be helpful for you to provide a tweaks.ini file at the root of the starter, and add the following line in the default `docker-compose.yml`, or instructions in the Readme.

```yml
volumes:
      - data:/data
      - ./tweaks.ini:/usr/local/etc/php/conf.d/tweaks.ini
```
What do you think?
Thanks.

**Comment by dsifford** [comment]
@louisremi All you should have to do with the setup in its current form is create a `*.ini` file somewhere at or below the root of your project and then create a volume to that file at `/usr/local/etc/php`.

So, in other words. Assuming you have a project that looks like this...

```
myproject
├── docker-compose.yml
├── php.ini
├── wp-content
│   ├── plugins
│   └── themes
└── package.json
```

create a volume like this

```yml
volumes:
    - ./php.ini:/usr/local/etc/php/php.ini`
```

You may or may not need to reload the apache service for that to take effect.

Hope that helps.

**Comment by louisremi** [comment]
Hi @dsifford,
Thanks, but I wasn't searching for a solution to my problem, I was rather suggesting that this file should exist by default, or this procedure should be documented somewhere, to save other people the time it took me to find the answer :-)
Also, if I use the .yml line you suggested instead of the one I was suggesting, won't I end up overriding the variable set by the dockerfile? `RUN echo "memory_limit = 512M" > /usr/local/etc/php/php.ini \`

**Comment by dsifford** [comment]
Send in a PR with changes to the readme and I'd be happy to merge.

Good point about the overwriting `php.ini`.. Forgot we had that in the dockerfile. In that case, you can just name it whatever you want and it should get picked up by apache as long as it has the `.ini` extension.
