### ISSUE TITLE
Should we consider adding certbot to this image for retrieving/renewing ssl certificates automatically using letsencrypt?

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#69]
@karellm I'm thinking about actually using this image for production use, but one key component it is lacking is an ability to easily get and renew SSL certs.

Would this be something you think we should add to this?

**Comment by karellm** [comment]
I think so yes. Maybe we could use Let's encrypt

**Comment by dsifford** [comment]
Yep, we sure can. I'm pretty sure I have an idea on how to go about it.

Want me to send a PR?
