### ISSUE TITLE
Preventing links from routing you from development site to actual deployed site?

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#7]
Hi again,

Still playing around with your image and I can't seem to figure out how one would prevent links from an imported site from navigating to the actual URL (instead of the local url). 

For example, the hosted site I would like to work on has an 'about' page at `www.mysite.com/about`. The links on the local site take me to the actual about page rather than `mycontainerip:8080/about`.

Any ideas?

**Comment by karellm** [comment]
@dsifford We haven't written about this just yet. The simplest (but manual) way could be to install [WP migrate db](https://en-ca.wordpress.org/plugins/wp-migrate-db/). It will let you do the search and replace while exporting the DB. So you can get a dump of your local development ready for production (and vice versa).

**Comment by dsifford** [comment]
Thanks for the tip. Not sure if that's going to work for me. Their pricing model is outrageous.

**Comment by karellm** [comment]
@dsifford You can use the free plugin, it lets you export and find/replace. Though it does not let you import it but you can do that another way (cli, phpmyadmin...).

**Comment by dsifford** [comment]
Ah, alright I'll give 'er a shot. Thanks for the help!

**Comment by karellm** [comment]
We are not paying for the pro version. The local development image comes with a script to reload the DB. You can read about it in the blog post listed in the README.

**Comment by dsifford** [comment]
@karellm You are a wizard, my friend. Your solution works wonderfully. Thank you!

On a different note: Let me know if your dockerhub Dockerfile is different than the one in this repo. Still having issues there (re: #4 ). 

Cheers! :beers:
