### ISSUE TITLE
Flew

### ISSUE THREAD

**Issue by karellm** [visiblevc/wordpress-starter#73]
@dsifford I got contact by the guys behind this: https://local.getflywheel.com/

Thought I would share, it looks interesting.

**Comment by dsifford** [comment]
Nice! What was it they contacted you about? Just pitching their project?

I recall seeing this on Product Hunt a couple months ago. Made me giggle. Looked like it was essentially this project, but for people who don't like to use the terminal. Never looked into it beyond there though.

**Comment by louisremi** [comment]
Only available for Mac and Windows :-/

**Comment by karellm** [comment]
Yeah they just wanted feedback on what they do and for me to talk about them in our blog articles. I personally have no time to spend on this at the moment but thought I'd share.

**Comment by dsifford** [comment]
What are they going to do for us? That's a shame. For a minute there I thought they might have been interested in joining forces.

**Comment by karellm** [comment]
No, that's not what's on the table at all. I don't see "competition" as an issue personally.
