### ISSUE TITLE
Suggestion: add Composer to the image

### ISSUE THREAD

**Issue by louisremi** [visiblevc/wordpress-starter#74]
Having PHP's Composer pre-installed in the image and adding a 'REQUIRE` property in the `docker-compose.yml` would be a very nice addition to this project I believe.

I'd like to use wordpress-starter to unit-test a plugin of mine. Having Composer pre-installed would allow me to quickly install PHPUnit and test my plugin.

I might give a PR a try, but I'd prefer to be sure that it has a chance of being accepted.

Thank you in advance :-)

**Comment by karellm** [comment]
I think that's a fair request. Happy to look at the PR 👍
