### ISSUE TITLE
Attempt #3 - Can I convince you to enable automatic builds?

### ISSUE THREAD

**Issue by dsifford** [visiblevc/wordpress-starter#75]
@karellm I'm beginning to notice a theme in the Dockerhub repo...

![image](https://cloud.githubusercontent.com/assets/5240018/22083990/4c7287fc-dd9c-11e6-9bef-b818f1f7ed70.png)

This can be completely solved by enabling automatic builds. Additionally, the `README.md` from github will stay synced with the Dockerhub readme. It's a win-win.

**Comment by karellm** [comment]
I will talk about this with the team.

**Comment by dsifford** [comment]
Nevermind. I'm going to start building to my own dockerhub account using this mirror I just set up: https://github.com/dsifford/wordpress-starter-mirror

**Comment by dsifford** [comment]
@karellm That said, I'd really prefer to autobuild from this repo because maintaining a mirror along with this repo is a bit overkill and sort of a pain.

I might end up forking to my own project again if this becomes too much of a hassle.

**Comment by dsifford** [comment]
Nevermind. I'm able to build automatically from this repository since I'm a contributor. https://hub.docker.com/r/dsifford/wordpress/
