### ISSUE TITLE
Sugestion: improve Development Instruction

### ISSUE THREAD

**Issue by louisremi** [visiblevc/wordpress-starter#80]
I'm making a lot of tweaks to the `Dockerfile` and `run.sh` files lately, and I was wasting a lot of time pushing run.sh on Github and building my image with `--no-cache`... until I realized that I could just volume run.sh, which, I believe, allows me to build my image without `--no-cache`.

Maybe the wiki could mention this simple trick to make local development of the project easier?

**Comment by karellm** [comment]
@louisremi I added a Development section in the wiki. Feel free to add the instructions you want there. Please try to keep the content short and sweet though, the goal is not to document all the Docker internals. Thanks!
