### ISSUE TITLE
Help Request: Adding xdebug to the image

### ISSUE THREAD

**Issue by louisremi** [visiblevc/wordpress-starter#81]
I'm working on adding xdebug to my image. I hoped I could simply switch the base image of this project to an image that includes xdebug, such as [MiLk/docker-php-xdebug](/MiLk/docker-php-xdebug). Unfortunately, none of the image or instructions I've found out there allowed me to successfully get xdebug to work.

I'll send a PR with the changes I've made to the Dockerfile. Any help would be greatly appreciated.

**Comment by louisremi** [comment]
See https://github.com/visiblevc/wordpress-starter/pull/82/files#diff-213510ff1a0954432e1f45c9d4f91c68

**Comment by karellm** [comment]
Please don't open both a PR and issue. Let's centralize the conversation to #82
