### ISSUE TITLE
WP-CLI: sudo command not found

### ISSUE THREAD

**Issue by Spone** [visiblevc/wordpress-starter#86]
Hello there,

## Overview

- **What's your problem about?** When I'm trying to run any WP-CLI command using `npm run wp ...` I'm getting the following error: `/bin/bash: sudo: command not found`
- **What is your operating system?** Ubuntu 16.04 LTS
- **What is your docker version?** `docker version 1.13.1, build 092cba3`

Can you help?

Thanks

**Comment by Cuchulain** [comment]
install *sudo* under *root* account:
`apt-get install sudo`
and then add Your _work_ account into *sudo* group.

**Comment by dsifford** [comment]
@Spone That's strange. `sudo` is most definitely installed in the container.

Can you tell me what version you're running? You can check by running the following command

```
$ docker inspect -f '{{ .Config.Labels.version }}' $(d ps -qf 'name=wordpress')
```

Also, can you open an interactive session inside the container and double check that sudo is not available?

```
$ docker exec -it $(docker ps -qf 'name=wordpress') /bin/bash
root@9eb59df5c81b:/app# which sudo
/usr/bin/sudo
```

Thanks

**Comment by Spone** [comment]
Thanks for the reply @dsifford 

    $ docker inspect -f '{{ .Config.Labels.version }}' $(docker ps -qf 'name=wordpress')
    <no value>
    0.14.0-php7.0

and

    docker exec -it $(docker ps -qf 'name=wordpress') /bin/bash
    rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"4a0dda2447f2\": executable file not found in $PATH"

**Comment by dsifford** [comment]
Is your wordpress container running? If so, can you restart your docker service to see if that helps? I've ran into this a couple times after updating Docker and the solution for me was to just reboot the service and daemon.

**Comment by Spone** [comment]
Thanks. Restarting Docker service fixed the issue, and I also manage to open the interactive session inside the container, but I had to change the name of the container:

    docker exec -it $(docker ps -qf 'name=wordpressstarter_wordpress_1') /bin/bash
