### ISSUE TITLE
small improvement to documentation DB_HOST

### ISSUE THREAD

**Issue by viennaoperator** [visiblevc/wordpress-starter#88]
Hello,
I was struggling to understand the DB_HOST variable and didn't know that it has to match the service name of the mysql/mariadb container. (because docker-compose automatically links the mysql/mariadb container via name in /etc/hosts within the wordpress container)

Maybe you can add this information in your documentation.

**Comment by dsifford** [comment]
@viennaoperator Open a pull request with your suggested changes and I'd be glad to merge it.
