### ISSUE TITLE
Missing Wordpress admin credentials

### ISSUE THREAD

**Issue by zela** [visiblevc/wordpress-starter#91]
Hi there!
I don't see any mentions of admin login and password for Wordpress installation, neither in README, nor in related blog posts. How to access `/wp-admin` area?

**Comment by dsifford** [comment]
Hm, you're right! Just checked the readme and I don't think we made it completely clear.

By default, the admin username is `root`, and the password is the same as `DB_PASS`.

If you import a database, usernames and passwords are the same as you would expect from the imported site.

Feel free to send a PR with documentation changes if you'd like. Hope the above explanation helps.
