### ISSUE TITLE
Configuring the php version not Documented

### ISSUE THREAD

**Issue by lukasholzer** [visiblevc/wordpress-starter#93]
**Hey I'm struggling to find out wich *php version* docker-compose is using.**

In the [README.md](https://github.com/visiblevc/wordpress-starter#available-images) there is a section called available images which are introducing the possibility of choosing one, unfortunately, it is not described to implement one solution. 

### There are two folders inside:

```
 - php5.6
  `- Dockerfile
 - php7.0
  `- Dockerfile
```

How can I configure to use php7.0 or php5.6?
There is no service specified in the `docker-compose.yml` to select this **Dockerimage**

**Comment by karellm** [comment]
In the Dockerfile:

```
services:
  wordpress:
    image: visiblevc/wordpress:latest #here you can replace latest with the version you want
```
